# Generated by Django 4.2 on 2026-02-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_add_severity_and_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosisrecord',
            name='confidence_level',
            field=models.CharField(choices=[('low', 'Low (< 60%)'), ('medium', 'Medium (60-80%)'), ('high', 'High (> 80%)')], editable=False, max_length=10),
        ),
    ]
